### ISSUE TITLE
command line request

### ISSUE THREAD

**Issue by raulpdlr** [evil-mad/stipplegen#16]
Hello, sometimes I find that the UI becomes unresponsive after moving the controls around.  Is there a way to run the application via command line with inputs and a file to simply get an output?  That would be awesome and I think many other users would benefit as well.

**Comment by oskay** [comment]
I'm not even sure what that would mean, since this is a program that you run until you like the output and then stop it. Without a GUI, there's no UX model to follow.

That said, some people do run Processing sketches from a terminal; here's one discussion on the topic:
https://stackoverflow.com/questions/14787093/how-to-run-processing-applications-from-the-terminal
